"""
Flask web application for viewing synthetic healthcare data.

This module provides a web interface to explore and visualize the synthetic healthcare data
generated by the data generation pipeline.
"""

import json
import os
import sys
from flask import Flask, render_template, jsonify, request, abort

# Add the parent directory to the Python path to allow imports from src
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from src.utils.file_utils import load_config

app = Flask(__name__)

# Configuration
OUTPUT_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'output')
PROCESSED_DIR = os.path.join(OUTPUT_DIR, 'processed')
RAW_DIR = os.path.join(OUTPUT_DIR, 'raw')
CONFIG_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'config', 'config.json')

# Load data files
def load_json_data(file_path):
    """Load JSON data from a file."""
    try:
        with open(file_path, 'r') as f:
            return json.load(f)
    except Exception as e:
        app.logger.error(f"Error loading data from {file_path}: {e}")
        return None

# Routes
@app.route('/')
def index():
    """Render the main dashboard page."""
    return render_template('modern_index.html')

@app.route('/members')
def members_page():
    """Render the members page."""
    return render_template('members.html')

@app.route('/member/<member_id>')
def member_view_page(member_id):
    """Render the member view page for a specific member."""
    try:
        # Load member data
        members = load_json_data(os.path.join(PROCESSED_DIR, 'members.json'))
        if members is None:
            app.logger.error(f"Failed to load members.json for member view page: {member_id}")
            # Create a placeholder member for the template
            member = {
                'id': member_id,
                'first_name': 'Unknown',
                'last_name': 'Member',
                'full_name': 'Unknown Member'
            }
            return render_template('modern_member_view.html', member=member, member_id=member_id, error="Failed to load member data")
        
        # Find the member
        member = None
        for m in members:
            if m.get('id') == member_id:
                member = m
                break
        
        if member is None:
            app.logger.error(f"Member not found in members.json: {member_id}")
            # Create a placeholder member for the template
            member = {
                'id': member_id,
                'first_name': 'Unknown',
                'last_name': 'Member',
                'full_name': 'Unknown Member'
            }
            return render_template('modern_member_view.html', member=member, member_id=member_id, error="Member not found")
        
        app.logger.info(f"Rendering member view page for: {member.get('first_name')} {member.get('last_name')}")
        return render_template('modern_member_view.html', member=member, member_id=member_id)
    
    except Exception as e:
        app.logger.error(f"Error rendering member view page: {str(e)}")
        # Create a placeholder member for the template
        member = {
            'id': member_id,
            'first_name': 'Error',
            'last_name': 'Loading',
            'full_name': 'Error Loading'
        }
        return render_template('modern_member_view.html', member=member, member_id=member_id, error=str(e))

@app.route('/claims')
def claims_page():
    """Render the claims page."""
    return render_template('claims.html')

@app.route('/authorizations')
def authorizations_page():
    """Render the authorizations page."""
    return render_template('authorizations.html')

@app.route('/clinical-notes')
def clinical_notes_page():
    """Render the clinical notes page."""
    return render_template('clinical_notes.html')

@app.route('/clinical-encounters')
def clinical_encounters_page():
    """Render the clinical encounters page."""
    return render_template('clinical_encounters.html')

@app.route('/care-plans')
def care_plans_page():
    """Render the care plans page."""
    return render_template('care_plans.html')

@app.route('/communications')
def communications_page():
    """Render the communications page."""
    return render_template('communications.html')

@app.route('/statistics')
def statistics_page():
    """Render the statistics page."""
    return render_template('statistics.html')

@app.route('/eobs')
def eobs_page():
    """Render the EOBs page."""
    return render_template('eobs.html')

@app.route('/patient-data')
def patient_data_page():
    """Render the patient-generated data page."""
    return render_template('patient_data.html')

@app.route('/care-episodes')
def care_episodes_page():
    """Render the care episodes page."""
    return render_template('care_episodes.html')

@app.route('/sdoh-assessments')
def sdoh_assessments_page():
    """Render the SDOH assessments page."""
    return render_template('sdoh_assessments.html')

@app.route('/risk-assessments')
def risk_assessments_page():
    """Render the risk assessments page."""
    return render_template('risk_assessments.html')

@app.route('/provider-network')
def provider_network_page():
    """Render the provider network page."""
    return render_template('provider_network.html')

@app.route('/pharmacy-benefit')
def pharmacy_benefit_page():
    """Render the pharmacy benefit page."""
    return render_template('pharmacy_benefit.html')

@app.route('/authorization-rules')
def authorization_rules_page():
    """Render the authorization rules page."""
    return render_template('authorization_rules.html')

# API Routes
@app.route('/api/members')
def get_members():
    """API endpoint to get member data."""
    members = load_json_data(os.path.join(PROCESSED_DIR, 'members.json'))
    if members is None:
        abort(500)
    
    # Log the first member to help debug structure issues
    if members and len(members) > 0:
        app.logger.debug(f"First member structure: {members[0]}")
    
    return jsonify(members)

@app.route('/api/members/<member_id>')
def get_member(member_id):
    """API endpoint to get a specific member's data."""
    members = load_json_data(os.path.join(PROCESSED_DIR, 'members.json'))
    if members is None:
        abort(500)
    
    for member in members:
        if member.get('id') == member_id:
            # Log the member structure to help debug issues
            app.logger.debug(f"Member {member_id} structure: {member}")
            return jsonify(member)
    
    abort(404)

@app.route('/api/claims')
def get_claims():
    """API endpoint to get claim data."""
    claims = load_json_data(os.path.join(PROCESSED_DIR, 'claims.json'))
    if claims is None:
        abort(500)
    return jsonify(claims)

@app.route('/api/claims/<claim_id>')
def get_claim(claim_id):
    """API endpoint to get a specific claim's data."""
    claims = load_json_data(os.path.join(PROCESSED_DIR, 'claims.json'))
    if claims is None:
        abort(500)
    
    for claim in claims:
        if claim.get('id') == claim_id:
            return jsonify(claim)
    
    abort(404)

@app.route('/api/authorizations')
def get_authorizations():
    """API endpoint to get authorization data."""
    authorizations = load_json_data(os.path.join(PROCESSED_DIR, 'authorizations.json'))
    if authorizations is None:
        abort(500)
    return jsonify(authorizations)

@app.route('/api/authorizations/<auth_id>')
def get_authorization(auth_id):
    """API endpoint to get a specific authorization's data."""
    authorizations = load_json_data(os.path.join(PROCESSED_DIR, 'authorizations.json'))
    if authorizations is None:
        abort(500)
    
    for auth in authorizations:
        if auth.get('id') == auth_id:
            return jsonify(auth)
    
    abort(404)

@app.route('/api/clinical-notes')
def get_clinical_notes():
    """API endpoint to get clinical note data."""
    notes = load_json_data(os.path.join(PROCESSED_DIR, 'clinical_notes.json'))
    if notes is None:
        abort(500)
    return jsonify(notes)

@app.route('/api/clinical-notes/<note_id>')
def get_clinical_note(note_id):
    """API endpoint to get a specific clinical note's data."""
    notes = load_json_data(os.path.join(PROCESSED_DIR, 'clinical_notes.json'))
    if notes is None:
        abort(500)
    
    for note in notes:
        if note.get('id') == note_id:
            return jsonify(note)
    
    abort(404)

@app.route('/api/clinical-encounters')
def get_clinical_encounters():
    """API endpoint to get clinical encounter data."""
    encounters = load_json_data(os.path.join(PROCESSED_DIR, 'clinical_encounters.json'))
    if encounters is None:
        abort(500)
    return jsonify(encounters)

@app.route('/api/clinical-encounters/<encounter_id>')
def get_clinical_encounter(encounter_id):
    """API endpoint to get a specific clinical encounter's data."""
    encounters = load_json_data(os.path.join(PROCESSED_DIR, 'clinical_encounters.json'))
    if encounters is None:
        abort(500)
    
    for encounter in encounters:
        if encounter.get('id') == encounter_id:
            return jsonify(encounter)
    
    abort(404)

@app.route('/api/care-plans')
def get_care_plans():
    """API endpoint to get care plan data."""
    plans = load_json_data(os.path.join(PROCESSED_DIR, 'care_plans.json'))
    if plans is None:
        abort(500)
    return jsonify(plans)

@app.route('/api/care-plans/<plan_id>')
def get_care_plan(plan_id):
    """API endpoint to get a specific care plan's data."""
    plans = load_json_data(os.path.join(PROCESSED_DIR, 'care_plans.json'))
    if plans is None:
        abort(500)
    
    for plan in plans:
        if plan.get('id') == plan_id:
            return jsonify(plan)
    
    abort(404)

@app.route('/api/communications')
def get_communications():
    """API endpoint to get communication data."""
    comms = load_json_data(os.path.join(PROCESSED_DIR, 'communications.json'))
    if comms is None:
        abort(500)
    
    # Process communications to add sender and recipient fields
    processed_comms = []
    for comm in comms:
        # Create a processed copy of the communication
        processed_comm = comm.copy()
        
        # Ensure member_id is present (even if null)
        if 'member_id' not in processed_comm:
            processed_comm['member_id'] = None
        
        # Determine sender and recipient based on communication type and direction
        comm_type = comm.get('communication_type', '')
        
        if comm_type == 'pharmacy_communication':
            # Handle pharmacy communications
            if 'pharmacy_id' in comm:
                processed_comm['sender'] = f"pharmacy: {comm.get('pharmacy_id', 'Unknown')}"
            else:
                processed_comm['sender'] = comm.get('sender', 'Unknown')
                
            if 'provider_id' in comm:
                processed_comm['recipient'] = f"provider: {comm.get('provider_id', 'Unknown')}"
            else:
                processed_comm['recipient'] = comm.get('recipient', 'Unknown')
        elif comm_type == 'provider_to_provider':
            # Handle provider-to-provider communications
            if 'provider_id' in comm:
                processed_comm['sender'] = f"provider: {comm.get('provider_id', 'Unknown')}"
            else:
                processed_comm['sender'] = comm.get('sender', 'Unknown')
                
            if 'recipient_provider_id' in comm:
                processed_comm['recipient'] = f"provider: {comm.get('recipient_provider_id', 'Unknown')}"
            else:
                processed_comm['recipient'] = comm.get('recipient', 'Unknown')
        elif comm_type == 'care_team_discussion':
            # Handle care team discussions
            if 'provider_id' in comm:
                processed_comm['sender'] = f"provider: {comm.get('provider_id', 'Unknown')}"
            else:
                processed_comm['sender'] = comm.get('sender', 'Unknown')
                
            if 'recipient_provider_id' in comm:
                processed_comm['recipient'] = f"provider: {comm.get('recipient_provider_id', 'Unknown')}"
            else:
                processed_comm['recipient'] = comm.get('recipient', 'Unknown')
        elif comm.get('direction') == 'provider_to_member':
            processed_comm['sender'] = comm.get('provider_id', 'Provider')
            processed_comm['recipient'] = comm.get('member_id', 'Member')
        elif comm.get('direction') == 'member_to_provider':
            processed_comm['sender'] = comm.get('member_id', 'Member')
            processed_comm['recipient'] = comm.get('provider_id', 'Provider')
        else:
            processed_comm['sender'] = comm.get('sender', 'Unknown')
            processed_comm['recipient'] = comm.get('recipient', 'Unknown')
        
        processed_comms.append(processed_comm)
    
    return jsonify(processed_comms)

@app.route('/api/communications/<comm_id>')
def get_communication(comm_id):
    """API endpoint to get a specific communication's data."""
    comms = load_json_data(os.path.join(PROCESSED_DIR, 'communications.json'))
    if comms is None:
        abort(500)
    
    for comm in comms:
        if comm.get('id') == comm_id:
            # Create a processed copy of the communication
            processed_comm = comm.copy()
            
            # Ensure member_id is present (even if null)
            if 'member_id' not in processed_comm:
                processed_comm['member_id'] = None
            
            # Determine sender and recipient based on communication type and direction
            comm_type = comm.get('communication_type', '')
            
            if comm_type == 'pharmacy_communication':
                # Handle pharmacy communications
                if 'pharmacy_id' in comm:
                    processed_comm['sender'] = f"pharmacy: {comm.get('pharmacy_id', 'Unknown')}"
                else:
                    processed_comm['sender'] = comm.get('sender', 'Unknown')
                    
                if 'provider_id' in comm:
                    processed_comm['recipient'] = f"provider: {comm.get('provider_id', 'Unknown')}"
                else:
                    processed_comm['recipient'] = comm.get('recipient', 'Unknown')
            elif comm_type == 'provider_to_provider':
                # Handle provider-to-provider communications
                if 'provider_id' in comm:
                    processed_comm['sender'] = f"provider: {comm.get('provider_id', 'Unknown')}"
                else:
                    processed_comm['sender'] = comm.get('sender', 'Unknown')
                    
                if 'recipient_provider_id' in comm:
                    processed_comm['recipient'] = f"provider: {comm.get('recipient_provider_id', 'Unknown')}"
                else:
                    processed_comm['recipient'] = comm.get('recipient', 'Unknown')
            elif comm_type == 'care_team_discussion':
                # Handle care team discussions
                if 'provider_id' in comm:
                    processed_comm['sender'] = f"provider: {comm.get('provider_id', 'Unknown')}"
                else:
                    processed_comm['sender'] = comm.get('sender', 'Unknown')
                    
                if 'recipient_provider_id' in comm:
                    processed_comm['recipient'] = f"provider: {comm.get('recipient_provider_id', 'Unknown')}"
                else:
                    processed_comm['recipient'] = comm.get('recipient', 'Unknown')
            elif comm.get('direction') == 'provider_to_member':
                processed_comm['sender'] = comm.get('provider_id', 'Provider')
                processed_comm['recipient'] = comm.get('member_id', 'Member')
            elif comm.get('direction') == 'member_to_provider':
                processed_comm['sender'] = comm.get('member_id', 'Member')
                processed_comm['recipient'] = comm.get('provider_id', 'Provider')
            else:
                processed_comm['sender'] = comm.get('sender', 'Unknown')
                processed_comm['recipient'] = comm.get('recipient', 'Unknown')
            
            return jsonify(processed_comm)
    
    abort(404)

@app.route('/api/eobs')
def get_eobs():
    """API endpoint to get explanation of benefits data."""
    eobs = load_json_data(os.path.join(PROCESSED_DIR, 'eobs.json'))
    if eobs is None:
        abort(500)
    return jsonify(eobs)

@app.route('/api/eobs/<eob_id>')
def get_eob(eob_id):
    """API endpoint to get a specific EOB's data."""
    eobs = load_json_data(os.path.join(PROCESSED_DIR, 'eobs.json'))
    if eobs is None:
        abort(500)
    
    for eob in eobs:
        if eob.get('id') == eob_id:
            return jsonify(eob)
    
    abort(404)

@app.route('/api/patient-generated-data')
def get_patient_generated_data():
    """API endpoint to get patient-generated data."""
    data = load_json_data(os.path.join(PROCESSED_DIR, 'patient_generated_data.json'))
    if data is None:
        abort(500)
    return jsonify(data)

@app.route('/api/patient-generated-data/<data_id>')
def get_patient_generated_data_item(data_id):
    """API endpoint to get a specific patient-generated data item."""
    data = load_json_data(os.path.join(PROCESSED_DIR, 'patient_generated_data.json'))
    if data is None:
        abort(500)
    
    for item in data:
        if item.get('id') == data_id:
            return jsonify(item)
    
    abort(404)

@app.route('/api/mental-health-narratives')
def get_mental_health_narratives():
    """API endpoint to get mental health narrative data."""
    narratives = load_json_data(os.path.join(PROCESSED_DIR, 'mental_health_narratives.json'))
    if narratives is None:
        abort(500)
    return jsonify(narratives)

@app.route('/api/telehealth-documentation')
def get_telehealth_documentation():
    """API endpoint to get telehealth documentation data."""
    docs = load_json_data(os.path.join(PROCESSED_DIR, 'telehealth_documentation.json'))
    if docs is None:
        abort(500)
    return jsonify(docs)

@app.route('/api/care-episodes')
def get_care_episodes():
    """API endpoint to get care episodes data."""
    episodes = load_json_data(os.path.join(PROCESSED_DIR, 'care_episodes.json'))
    if episodes is None:
        abort(500)
    return jsonify(episodes)

@app.route('/api/care-episodes/<episode_id>')
def get_care_episode(episode_id):
    """API endpoint to get a specific care episode's data."""
    episodes = load_json_data(os.path.join(PROCESSED_DIR, 'care_episodes.json'))
    if episodes is None:
        abort(500)
    
    for episode in episodes:
        if episode.get('id') == episode_id:
            return jsonify(episode)
    
    abort(404)

@app.route('/api/sdoh-assessments')
def get_sdoh_assessments():
    """API endpoint to get SDOH assessments data."""
    assessments = load_json_data(os.path.join(PROCESSED_DIR, 'sdoh_assessments.json'))
    if assessments is None:
        abort(500)
    return jsonify(assessments)

@app.route('/api/sdoh-assessments/<assessment_id>')
def get_sdoh_assessment(assessment_id):
    """API endpoint to get a specific SDOH assessment's data."""
    assessments = load_json_data(os.path.join(PROCESSED_DIR, 'sdoh_assessments.json'))
    if assessments is None:
        abort(500)
    
    for assessment in assessments:
        if assessment.get('id') == assessment_id:
            return jsonify(assessment)
    
    abort(404)

@app.route('/api/risk-assessments')
def get_risk_assessments():
    """API endpoint to get risk assessments data."""
    assessments = load_json_data(os.path.join(PROCESSED_DIR, 'risk_assessments.json'))
    if assessments is None:
        abort(500)
    return jsonify(assessments)

@app.route('/api/risk-assessments/<assessment_id>')
def get_risk_assessment(assessment_id):
    """API endpoint to get a specific risk assessment's data."""
    assessments = load_json_data(os.path.join(PROCESSED_DIR, 'risk_assessments.json'))
    if assessments is None:
        abort(500)
    
    for assessment in assessments:
        if assessment.get('id') == assessment_id:
            return jsonify(assessment)
    
    abort(404)

@app.route('/api/provider-network')
def get_provider_network():
    """API endpoint to get provider network data."""
    network = load_json_data(os.path.join(PROCESSED_DIR, 'provider_network.json'))
    if network is None:
        abort(500)
    return jsonify(network)

@app.route('/api/pharmacy-benefit')
def get_pharmacy_benefit():
    """API endpoint to get pharmacy benefit data."""
    benefit = load_json_data(os.path.join(PROCESSED_DIR, 'pharmacy_benefit.json'))
    if benefit is None:
        abort(500)
    return jsonify(benefit)

@app.route('/api/authorization-rules')
def get_authorization_rules():
    """API endpoint to get authorization rules data."""
    rules = load_json_data(os.path.join(PROCESSED_DIR, 'authorization_rules.json'))
    if rules is None:
        abort(500)
    return jsonify(rules)
@app.route('/api/statistics')
def get_statistics():
    """API endpoint to get statistics data."""
    stats = load_json_data(os.path.join(OUTPUT_DIR, 'statistics.json'))
    if stats is None:
        abort(500)
    
    # Get period parameter (monthly, quarterly, yearly)
    period = request.args.get('period', 'monthly')
    
    # Add additional statistics for the dashboard
    # 1. Claims by month/quarter/year
    claims = load_json_data(os.path.join(PROCESSED_DIR, 'claims.json'))
    if claims:
        # Process claims data to get distribution by time period
        claims_by_month = process_claims_by_time_period(claims, period)
        stats['claims_by_month'] = claims_by_month
        
        # Process claims data to get status distribution
        claim_status_counts = {}
        for claim in claims:
            status = claim.get('status', 'Unknown')
            claim_status_counts[status] = claim_status_counts.get(status, 0) + 1
        
        claim_status_distribution = [
            {'status': status, 'count': count}
            for status, count in claim_status_counts.items()
        ]
        stats['claim_status_distribution'] = claim_status_distribution
        
        # Process claims data to get top diagnoses
        diagnosis_counts = {}
        for claim in claims:
            diagnosis_codes = claim.get('diagnosis_codes', [])
            for code in diagnosis_codes:
                diagnosis_counts[code] = diagnosis_counts.get(code, 0) + 1
        
        # Sort by count and take top 10
        top_diagnoses = [
            {'code': code, 'count': count, 'description': get_diagnosis_description(code)}
            for code, count in sorted(diagnosis_counts.items(), key=lambda x: x[1], reverse=True)[:10]
        ]
        stats['top_diagnoses'] = top_diagnoses
    
    # 2. Authorization types
    authorizations = load_json_data(os.path.join(PROCESSED_DIR, 'authorizations.json'))
    if authorizations:
        auth_type_counts = {}
        for auth in authorizations:
            # Check for service_lines which contain service_type
            service_lines = auth.get('service_lines', [])
            if service_lines:
                for service_line in service_lines:
                    service_type = service_line.get('service_type', 'Unknown')
                    auth_type_counts[service_type] = auth_type_counts.get(service_type, 0) + 1
            else:
                # Fallback to top-level type if it exists
                auth_type = auth.get('type', 'Unknown')
                auth_type_counts[auth_type] = auth_type_counts.get(auth_type, 0) + 1
        
        authorization_types = [
            {'type': auth_type, 'count': count}
            for auth_type, count in auth_type_counts.items()
        ]
        stats['authorization_types'] = authorization_types
    
    # 3. Member age distribution
    members = load_json_data(os.path.join(PROCESSED_DIR, 'members.json'))
    if members:
        age_ranges = {
            '0-17': 0,
            '18-34': 0,
            '35-50': 0,
            '51-65': 0,
            '66+': 0
        }
        
        for member in members:
            age = member.get('age', 0)
            if age < 18:
                age_ranges['0-17'] += 1
            elif age < 35:
                age_ranges['18-34'] += 1
            elif age < 51:
                age_ranges['35-50'] += 1
            elif age < 66:
                age_ranges['51-65'] += 1
            else:
                age_ranges['66+'] += 1
        
        member_age_distribution = [
            {'range': age_range, 'count': count}
            for age_range, count in age_ranges.items()
        ]
        stats['member_age_distribution'] = member_age_distribution
    
    return jsonify(stats)

def process_claims_by_time_period(claims, period='monthly'):
    """Process claims data to get distribution by time period."""
    from datetime import datetime
    import calendar
    
    # Initialize result
    time_period_counts = {}
    
    for claim in claims:
        date_str = claim.get('date_received') or claim.get('submission_date')
        if not date_str:
            continue
        
        try:
            date = datetime.fromisoformat(date_str.replace('Z', '+00:00'))
            
            if period == 'monthly':
                # Format: "Jan 2025"
                period_key = date.strftime('%b %Y')
            elif period == 'quarterly':
                # Calculate quarter (1-4)
                quarter = (date.month - 1) // 3 + 1
                # Format: "Q1 2025"
                period_key = f"Q{quarter} {date.year}"
            elif period == 'yearly':
                # Format: "2025"
                period_key = str(date.year)
            else:
                # Default to monthly
                period_key = date.strftime('%b %Y')
            
            time_period_counts[period_key] = time_period_counts.get(period_key, 0) + 1
        except (ValueError, TypeError):
            # Skip invalid dates
            continue
    
    # Convert to sorted list of dictionaries
    result = []
    
    if period == 'monthly':
        # Sort by year and month
        sorted_periods = sorted(time_period_counts.keys(),
                               key=lambda x: datetime.strptime(x, '%b %Y'))
    elif period == 'quarterly':
        # Sort by year and quarter
        sorted_periods = sorted(time_period_counts.keys(),
                               key=lambda x: (int(x.split()[-1]), int(x[1])))
    elif period == 'yearly':
        # Sort by year
        sorted_periods = sorted(time_period_counts.keys(), key=int)
    else:
        # Default sort
        sorted_periods = sorted(time_period_counts.keys())
    
    for period_key in sorted_periods:
        result.append({
            'period': period_key,
            'month': period_key,  # For backward compatibility
            'count': time_period_counts[period_key]
        })
    
    return result

def get_diagnosis_description(code):
    """Get a description for a diagnosis code. This is a placeholder function."""
    # In a real application, this would look up the description from a database or API
    # For now, we'll return a placeholder
    return f"Diagnosis {code}"

@app.route('/api/member/<member_id>/related')
def get_member_related_data(member_id):
    """API endpoint to get all data related to a specific member."""
    try:
        app.logger.info(f"Loading related data for member {member_id}")
        
        # Load all data types
        members = load_json_data(os.path.join(PROCESSED_DIR, 'members.json'))
        if members is None:
            app.logger.error("Failed to load members.json")
            members = []
            
        claims = load_json_data(os.path.join(PROCESSED_DIR, 'claims.json')) or []
        authorizations = load_json_data(os.path.join(PROCESSED_DIR, 'authorizations.json')) or []
        clinical_notes = load_json_data(os.path.join(PROCESSED_DIR, 'clinical_notes.json')) or []
        clinical_encounters = load_json_data(os.path.join(PROCESSED_DIR, 'clinical_encounters.json')) or []
        care_plans = load_json_data(os.path.join(PROCESSED_DIR, 'care_plans.json')) or []
        communications = load_json_data(os.path.join(PROCESSED_DIR, 'communications.json')) or []
        eobs = load_json_data(os.path.join(PROCESSED_DIR, 'eobs.json')) or []
        patient_data = load_json_data(os.path.join(PROCESSED_DIR, 'patient_generated_data.json')) or []
        mental_health = load_json_data(os.path.join(PROCESSED_DIR, 'mental_health_narratives.json')) or []
        telehealth = load_json_data(os.path.join(PROCESSED_DIR, 'telehealth_documentation.json')) or []
        
        # Load Phase 7 data types
        care_episodes = load_json_data(os.path.join(PROCESSED_DIR, 'care_episodes.json')) or []
        sdoh_assessments = load_json_data(os.path.join(PROCESSED_DIR, 'sdoh_assessments.json')) or []
        risk_assessments = load_json_data(os.path.join(PROCESSED_DIR, 'risk_assessments.json')) or []
        
        # Load pharmacy benefit data
        pharmacy_benefit = load_json_data(os.path.join(PROCESSED_DIR, 'pharmacy_benefit.json')) or {}
        pharmacy_claims = pharmacy_benefit.get('pharmacy_claims', [])
        
        app.logger.info(f"Loaded data files successfully. Found {len(members)} members.")
        
        # Find the member
        member = None
        for m in members:
            if m.get('id') == member_id:
                member = m
                break
        
        if member is None:
            app.logger.error(f"Member {member_id} not found in members.json")
            abort(404)
        
        # Log the member structure to help debug issues
        app.logger.info(f"Found member {member_id}: {member.get('first_name')} {member.get('last_name')}")
        
        # Check if gender, plan_name, and effective_date are present
        app.logger.debug(f"Member gender: {member.get('gender', 'NOT FOUND')}")
        app.logger.debug(f"Member insurance: {member.get('insurance', 'NOT FOUND')}")
        if member.get('insurance'):
            app.logger.debug(f"Member plan_name: {member['insurance'].get('plan_name', 'NOT FOUND')}")
            app.logger.debug(f"Member effective_date: {member['insurance'].get('effective_date', 'NOT FOUND')}")
        
        # Find related data
        member_claims = [c for c in claims if c.get('member_id') == member_id]
        member_auths = [a for a in authorizations if a.get('member_id') == member_id]
        member_notes = [n for n in clinical_notes if n.get('member_id') == member_id]
        member_encounters = [e for e in clinical_encounters if e.get('member_id') == member_id]
        member_plans = [p for p in care_plans if p.get('member_id') == member_id]
        
        # Process communications to add sender and recipient fields
        member_comms = []
        for c in communications:
            if c.get('member_id') == member_id:
                # Create a processed copy of the communication
                processed_comm = c.copy()
                
                # Ensure member_id is set
                processed_comm['member_id'] = member_id
                
                # Determine sender and recipient based on communication type and direction
                comm_type = c.get('communication_type', '')
                
                if comm_type == 'pharmacy_communication':
                    # Handle pharmacy communications
                    if 'pharmacy_id' in c:
                        processed_comm['sender'] = f"pharmacy: {c.get('pharmacy_id', 'Unknown')}"
                    else:
                        processed_comm['sender'] = c.get('sender', 'Unknown')
                        
                    if 'provider_id' in c:
                        processed_comm['recipient'] = f"provider: {c.get('provider_id', 'Unknown')}"
                    else:
                        processed_comm['recipient'] = c.get('recipient', 'Unknown')
                elif comm_type == 'provider_to_provider':
                    # Handle provider-to-provider communications
                    if 'provider_id' in c:
                        processed_comm['sender'] = f"provider: {c.get('provider_id', 'Unknown')}"
                    else:
                        processed_comm['sender'] = c.get('sender', 'Unknown')
                    
                    if 'recipient_provider_id' in c:
                        processed_comm['recipient'] = f"provider: {c.get('recipient_provider_id', 'Unknown')}"
                    else:
                        processed_comm['recipient'] = c.get('recipient', 'Unknown')
                elif comm_type == 'care_team_discussion':
                    # Handle care team discussions
                    if 'provider_id' in c:
                        processed_comm['sender'] = f"provider: {c.get('provider_id', 'Unknown')}"
                    else:
                        processed_comm['sender'] = c.get('sender', 'Unknown')
                        
                    if 'recipient_provider_id' in c:
                        processed_comm['recipient'] = f"provider: {c.get('recipient_provider_id', 'Unknown')}"
                    else:
                        processed_comm['recipient'] = c.get('recipient', 'Unknown')
                elif c.get('direction') == 'provider_to_member':
                    processed_comm['sender'] = c.get('provider_id', 'Provider')
                    processed_comm['recipient'] = f"Member {member_id}"
                elif c.get('direction') == 'member_to_provider':
                    processed_comm['sender'] = f"Member {member_id}"
                    processed_comm['recipient'] = c.get('provider_id', 'Provider')
                else:
                    processed_comm['sender'] = c.get('sender', 'Unknown')
                    processed_comm['recipient'] = c.get('recipient', 'Unknown')
                
                member_comms.append(processed_comm)
        
        member_eobs = [e for e in eobs if e.get('member_id') == member_id]
        member_patient_data = [p for p in patient_data if p.get('member_id') == member_id]
        member_mental_health = [m for m in mental_health if m.get('member_id') == member_id]
        member_telehealth = [t for t in telehealth if t.get('member_id') == member_id]
        
        # Find related Phase 7 data
        member_care_episodes = [e for e in care_episodes if e.get('member_id') == member_id]
        member_sdoh_assessments = [a for a in sdoh_assessments if a.get('member_id') == member_id]
        member_risk_assessments = [a for a in risk_assessments if a.get('member_id') == member_id]
        
        
        # Find related pharmacy claims
        member_pharmacy_claims = [c for c in pharmacy_claims if c.get('member_id') == member_id]
        
        # Compile results
        result = {
            'member': member,
            'claims': member_claims,
            'authorizations': member_auths,
            'clinical_notes': member_notes,
            'clinical_encounters': member_encounters,
            'care_plans': member_plans,
            'communications': member_comms,
            'eobs': member_eobs,
            'patient_generated_data': member_patient_data,
            'mental_health_narratives': member_mental_health,
            'telehealth_documentation': member_telehealth,
            # Phase 7 data
            'care_episodes': member_care_episodes,
            'sdoh_assessments': member_sdoh_assessments,
            'risk_assessments': member_risk_assessments,
            # Pharmacy data
            'pharmacy_claims': member_pharmacy_claims
        }
        
        app.logger.info(f"Successfully compiled related data for member {member_id}")
        return jsonify(result)
    
    except Exception as e:
        app.logger.error(f"Error getting related data for member {member_id}: {str(e)}")
        return jsonify({
            'error': 'Failed to load member data',
            'message': str(e),
            'member': {
                'id': member_id,
                'first_name': 'Error',
                'last_name': 'Loading Data',
                'age': 0,
                'gender': 'Unknown',
                'address': {
                    'street': '',
                    'city': '',
                    'state': '',
                    'zip': ''
                },
                'insurance': {
                    'member_id': member_id
                }
            },
            'claims': [],
            'authorizations': [],
            'clinical_notes': [],
            'clinical_encounters': [],
            'care_plans': [],
            'communications': [],
            'eobs': [],
            'patient_generated_data': [],
            'mental_health_narratives': [],
            'telehealth_documentation': [],
            'care_episodes': [],
            'sdoh_assessments': [],
            'risk_assessments': [],
            'pharmacy_claims': []
        }), 500

if __name__ == '__main__':
    # Load configuration
    config = load_config(CONFIG_PATH)
    
    # Get port from config or use default
    port = config.get('web_config', {}).get('port', 5000)
    
    # Run the application
    app.run(debug=True, port=port)